// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1_NFZMmX6ADDuABGTrDeJGLGr0BYctaI',
    appId: '1:1031232343907:web:bf4f2f83f02baa66eacd56',
    messagingSenderId: '1031232343907',
    projectId: 'elresala-d01eb',
    authDomain: 'elresala-d01eb.firebaseapp.com',
    storageBucket: 'elresala-d01eb.appspot.com',
    measurementId: 'G-KWSCBGQGWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPFsw8V_l16jfSmR0BnsHFcTO8jPdYgJk',
    appId: '1:1031232343907:android:92d02c3083270045eacd56',
    messagingSenderId: '1031232343907',
    projectId: 'elresala-d01eb',
    storageBucket: 'elresala-d01eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkXtGSlvyO4brKmr8TIa4eVRl-bw21LfA',
    appId: '1:1031232343907:ios:92a1c0dc100537e1eacd56',
    messagingSenderId: '1031232343907',
    projectId: 'elresala-d01eb',
    storageBucket: 'elresala-d01eb.appspot.com',
    iosBundleId: 'com.example.elresala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkXtGSlvyO4brKmr8TIa4eVRl-bw21LfA',
    appId: '1:1031232343907:ios:5b31d5a6b1db3995eacd56',
    messagingSenderId: '1031232343907',
    projectId: 'elresala-d01eb',
    storageBucket: 'elresala-d01eb.appspot.com',
    iosBundleId: 'com.example.elresala.RunnerTests',
  );
}
